// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace mb_lib
{ 
    public partial class bloggingContext : DbContext
    {
        public bloggingContext()
        {
        }

        public bloggingContext(DbContextOptions<bloggingContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Register> Registers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Comment>(entity =>
            {
                entity.Property(e => e.Comments).IsUnicode(false);

                entity.Property(e => e.Date).HasColumnType("datetime");

                entity.HasOne(d => d.CommentOwner)
                    .WithMany(p => p.Comments)
                    .HasForeignKey(d => d.CommentOwnerId)
                    .HasConstraintName("FK__Comments__Commen__3B75D760");

                entity.HasOne(d => d.Post)
                    .WithMany(p => p.Comments)
                    .HasForeignKey(d => d.PostId)
                    .HasConstraintName("FK__Comments__PostId__3C69FB99");
            });

            modelBuilder.Entity<Post>(entity =>
            {
                entity.ToTable("Post");

                entity.Property(e => e.Category)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Date).HasColumnType("datetime");

                entity.Property(e => e.Location)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Post1)
                    .IsUnicode(false)
                    .HasColumnName("Post");

                entity.HasOne(d => d.PostOwner)
                    .WithMany(p => p.Posts)
                    .HasForeignKey(d => d.PostOwnerId)
                    .HasConstraintName("FK__Post__PostOwnerI__38996AB5");
            });

            modelBuilder.Entity<Register>(entity =>
            {
                entity.HasKey(e => e.UserId)
                    .HasName("PK__Register__1788CC4C88C71382");

                entity.ToTable("Register");

                entity.Property(e => e.Email)
                    .HasMaxLength(75)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Password)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}