// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mb_lib
{
    public partial class Comment
    {
        public long CommentId { get; set; }
        public long? CommentOwnerId { get; set; }
        public long? PostId { get; set; }
        public string Comments { get; set; }
        public DateTime? Date { get; set; }

        public virtual Register CommentOwner { get; set; }
        public virtual Post Post { get; set; }
    }
}